apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-service
spec:
  type: NodePort
  selector:
    app: rollout-canary
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # Specify the nodePort value you prefer
